# Generated by Django 5.1.1 on 2024-09-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="brand",
            table="brand",
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AlterModelTable(
            name="subcategory",
            table="subcategory",
        ),
    ]
