# Generated by Django 5.1.1 on 2024-09-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_brand_table_alter_category_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="viewed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.category",
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
