# Generated by Django 5.1.1 on 2024-09-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_remove_product_brand_alter_product_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
