# Generated by Django 5.1.1 on 2024-10-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_product_author_product_cover_type_product_dimensions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
