# Generated by Django 5.1.1 on 2024-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="new_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="price_origin",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
