# Generated by Django 5.1.1 on 2024-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_alter_product_description"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(
                blank=True, related_name="product_promotions", to="promotion.promotion"
            ),
        ),
    ]
