# Generated by Django 5.1.1 on 2024-11-07 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_product_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="book.subcategory",
            ),
        ),
    ]
