# Generated by Django 5.1.1 on 2024-11-13 07:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_product_sub_category'),
        ('promotion', '0004_promotion_image_promotion_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': ' Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sách'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Danh mục con'},
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Loại bìa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô Tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kích thước'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Xóa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(verbose_name='Giá khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_origin',
            field=models.IntegerField(verbose_name='Giá gốc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='product_promotions', to='promotion.promotion', verbose_name='Các khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Năm xuất bản'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reprint_edition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tái bản'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='book.subcategory', verbose_name='Danh mục con'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewed',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
    ]
