# Generated by Django 5.1.1 on 2024-11-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_category_options_alter_product_options_and_more'),
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AddField(
            model_name='rating',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Tắt phản hồi'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='feed_back',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhận xét'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='Xóa'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.product', verbose_name='Sách'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(verbose_name='Xếp hạng'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='Phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rating.rating', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người phản hồi')),
            ],
            options={
                'verbose_name_plural': 'Phản hồi cho đánh giá',
                'db_table': 'rating_response',
                'ordering': ['created_at'],
            },
        ),
    ]
