# Generated by Django 5.1.1 on 2024-11-08 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
