# Generated by Django 5.1.1 on 2024-11-13 07:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_category_options_alter_product_options_and_more'),
        ('promotion', '0004_promotion_image_promotion_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'Khuyến mãi'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.IntegerField(verbose_name='Phần trăm khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotion_products', to='book.product', verbose_name='Sách'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('product', 'Giảm giá cho các sản phẩm'), ('subcategory', 'Giảm giá cho danh mục sản phẩm')], default='product', max_length=20, verbose_name='Loại khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='promotion_subcategories', to='book.subcategory', verbose_name='Danh mục con'),
        ),
    ]
