# Generated by Django 5.1.1 on 2024-10-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
