# Generated by Django 5.1.1 on 2024-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_cart_total_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
