# Generated by Django 5.1.1 on 2024-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_cartitem_is_delete_cartitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
