# Generated by Django 5.1.1 on 2024-11-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Phân quyền'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': 'Token tài khoản'},
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='user.role', verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
    ]
