# Generated by Django 5.1.1 on 2024-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_account_options_alter_role_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
