# Generated by Django 5.1.1 on 2024-09-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_status_account_is_active_account_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
    ]
