# Generated by Django 5.1.1 on 2024-09-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_account_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_active",
            new_name="status",
        ),
    ]
